[build]
  command = "pnpm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  PNPM_VERSION = "8"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Cache configuration
[[build.cache]]
  path = ".next/cache"
  ttl = 7d

[[build.cache]]
  path = "node_modules/.cache"
  ttl = 7d

[[build.cache]]
  path = ".pnpm-store"
  ttl = 7d 